<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class controlPowerDetail extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('product')->insert([
            [
                "name" => "AFP CR193B 10765",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "10765",
                "type" => "CR193B",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "AFP",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 KVA, 2400V, 115/230V, 1 Phase, 50/60Hz",
                "additionalKeywords" => "573A350P44, 870010765, 10765 (A-B), 9T24Y288",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/10765.jpg"
            ],
            [
                "name" => "Cutler-Hammer SJA-50 3405D92G01",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "3405D92G01",
                "type" => "SJA-50",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, 2300 pri., 120V sec. Also found on Westinghouse LF series. Equal to the alternative Westinghouse model #6406D14G01 (750VA) and Cutler-Hammer SJ models #2147A11G01 and #C7-E1D1C2 (both 0.75kVA).",
                "additionalKeywords" => "6406D14G01, 3405D92G01, 2147A11G01, MC.C7.A1D1C2, W341763748-00001, C7.5A1D1C2, 3405D92H01.",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/3405D92G01.jpg"
            ],
            [
                "name" => "Cutler-Hammer SL C20A1D1C2",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "C20A1D1C2",
                "type" => "SL",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, PRI: 2400V SEC: 120V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/C20A1D1C2.jpg"
            ],
            [
                "name" => "Cutler-Hammer SJS-50 C20E1D1C2",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "C20E1D1C2",
                "type" => "SJS-50",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, Pri. 4160VAC, Sec. 120VAC",
                "additionalKeywords" => "3351D67G03",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/C20E1D1C2.jpg"
            ],
            [
                "name" => "Cutler-Hammer SL C20K1D1C2",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "C20K1D1C2",
                "type" => "SL",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, PRI: 6600V, SEC: 120V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/C20K1D1C2.jpg"
            ],
            [
                "name" => "Cutler-Hammer SL-50 C.75A1D1C2",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "C7.5A1D1C2",
                "type" => "SL-50",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, 2400V-120V",
                "additionalKeywords" => "3405D92G01, , C7.5A1D1F2, 6406D14G01",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/C7.5A1D1C2.jpg"
            ],
            [
                "name" => "Eaton SL/SJ C7.5A1D1F2",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "C7.5A1D1F2",
                "type" => "SL / SJ",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Eaton",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, 2400V Pri, 120V Sec.",
                "additionalKeywords" => "3405D92G01, 6406D14G01",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/C7.5A1D1F2.jpg"
            ],
            [
                "name" => "General Electric CR193 302A3600VTP2",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "302A3600VTP2",
                "type" => "CR193",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "1.0 kVA, 2300V - 115/230V, 60Hz",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/302A3600VTP2.jpg"
            ],
            [
                "name" => "General Electric CR193 302A3600VTPI",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "302A3600VTPI",
                "type" => "CR193",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "1.0 kVA, 4160V,115/230V, 60Hz",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/302A3600VTPI.jpg"
            ],
            [
                "name" => "Allen Bradley 1502 Vacuum 25638-510-01",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25638-510-01",
                "type" => "1502 Vacuum",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "1.0 kVA, 2400V pri., 120V sec., 1φ, 60Hz.",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25638-510-01.jpg"
            ],
            [
                "name" => "Allen Bradley 1500/1502 Air 25638-570-01",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25638-570-01",
                "type" => "1500 / 1502 Air",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, 2400V pri., 120V sec., 60Hz.",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25638-570-01.jpg"
            ],
            [
                "name" => "Allen Bradley 1502 Vacuum 80022-154-03",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "80022-154-03",
                "type" => "1502 Vacuum",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "1.0 kVA, 4200V-115/230V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/80022-154-03.jpg"
            ],
            [
                "name" => "Allen Bradley 456-D X453105",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "X453105",
                "type" => "456-D",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, 2400V pri., 120V sec., 60Hz. Catalog no. X463298",
                "additionalKeywords" => "27289, CPT",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/X453105.jpg"
            ],
            [
                "name" => "Allis Chalmers 456-D 14-223-304-001U",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "14-223-304-001U",
                "type" => "456-D",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allis Chalmers",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 KVA, 2400-115/230V",
                "additionalKeywords" => "14-223-304-001, CPT",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/14-223-304-001U.jpg"
            ],
            [
                "name" => "Gould 7850 Air 700-243355",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "700-243355",
                "type" => "7850 Air",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Gould",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "1.0 kVA, 4160V-120V",
                "additionalKeywords" => "243355, I-T-E",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/700.jpg"
            ],
            [
                "name" => "Hammond 90H35 25-213-133-010",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-213-133-010",
                "type" => "90H35",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Hammond",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, 2300v 230VAC",
                "additionalKeywords" => "NH 3414L91",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-213-133-010.jpg"
            ],
            [
                "name" => "Hammond SJA/SJS/SJD/SL PT50PG",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "PT50PG",
                "type" => "SJA/SJS/SJD/SL",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Hammond",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "50 VA, 120/240V to 24VAC",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "3.6 pounds",
                "image" => "img/product/Control Power Transformer/PT50PG.jpg"
            ],
            [
                "name" => "Intrument Transformers CPT3-60-1.0-242FF",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "CPT3-60-1.0-242FF",
                "type" => "DV/DF",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Instrument Transformers",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "1.0 kVA, 2400:120V, 60Hz, 5kV 60kV BIL",
                "additionalKeywords" => "PC33220P105",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/CPT3-60-1.0-242FF.jpg"
            ],
            [
                "name" => "Siemens 456-D 25-205-350-001",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-205-350-001",
                "type" => "456-D",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75kVA, 2400V, 115V.A.C.",
                "additionalKeywords" => "CPT",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-205-350-001.jpg"
            ],
            [
                "name" => "Siemens 456-D 25-205-350-002",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-205-350-002",
                "type" => "456-D",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, Pri. 4160V, Sec. 115V.A.C.",
                "additionalKeywords" => "CPT",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-205-350-002.jpg"
            ],
            [
                "name" => "Siemens 81H3 25-205-607-001",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-205-607-001",
                "type" => "81H3",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, 2300V-115V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-205-607-001.jpg"
            ],
            [
                "name" => "Siemens 81H3 25-205-607-005",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-205-607-005",
                "type" => "81H3",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, 2300 Pri. V, 115 V.A.C. Sec., 60Hz",
                "additionalKeywords" => "CPT",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-205-607-005.jpg"
            ],
            [
                "name" => "Siemens 81H3 25-205-607-009",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-205-607-009",
                "type" => "81H3",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, PRI: 2300V SEC: 115V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-205-607-009.jpg"
            ],
            [
                "name" => "Siemens 81H3 25-205-607-013",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-205-607-013",
                "type" => "81H3",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => ".75kVA, 4000Pri., 115vAC Sec.",
                "additionalKeywords" => "CPT",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-205-607-013.jpg"
            ],
            [
                "name" => "Siemens 81H3 25-205-607-018",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-205-607-018",
                "type" => "81H3",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, PRI: 4000V, SEC: 230V!",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-205-607-018.jpg"
            ],
            [
                "name" => "AFP 97H35 CPTAFP13476",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "CPTAFP13476",
                "type" => "97H35",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "AFP",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, PRI: 4000V, SEC: 115/230V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/CPTAFP13476_front.jpg"
            ],
            [
                "name" => "Micron 456-D H750-0030",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "H750-0030",
                "type" => "456-D",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Micron",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVa, Pri. 4200V, Sec. 120V",
                "additionalKeywords" => "715-2036",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/H750-0030.jpg"
            ],
            [
                "name" => "Siemens 93H35 25-213-133-013",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-213-133-013",
                "type" => "93H35",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, Pri 4000V, Sec. 115, 60 Hz",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-213-133-013_front.jpg"
            ],
            [
                "name" => "Siemens 90H35 25-213-133-021",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-213-133-021",
                "type" => "90H35",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, PRI: 4000V, SEC: 115V, 60 Hz.",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-213-133-021_front.jpg"
            ],
            [
                "name" => "Siemens 90H35 25-213-133-027",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-213-133-027",
                "type" => "90H35",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "1.5 kVA, Pri. 4600V, Sec. 115V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-213-133-027.jpg"
            ],
            [
                "name" => "Siemens Allis 81H3 25-205-607-021",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-205-607-021",
                "type" => "81H3",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens Allis",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, 4000V-115V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-205-607-021_front.jpg"
            ],
            [
                "name" => "Square D 8110 Vacuum 52911-025-50",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "52911-025-50",
                "type" => "8110 Vacuum",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Square D",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "1.5 kVA, Pri. 2400VAC, Sec. 120VAC",
                "additionalKeywords" => "Neco Hammond, 71956C90",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/52911-025-50.jpg"
            ],
            [
                "name" => "Toshiba DV/DF PC3220P105",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "PC33220P105",
                "type" => "DV/DF",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Toshiba",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "5.0 kVA, Pri. 2400, Sec. 120 V, 60Hz, 5kV 60kV BIL",
                "additionalKeywords" => "CPT3-60-0.5-242CC",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/PC33220P105.jpg"
            ],
            [
                "name" => "Toshiba DV/DF V-E2HDP",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "V-E2HDP",
                "type" => "DV/DF",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Toshiba",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "100 VA, 2.4 V pri. / 120 V sec., 50/60 Hz, Ins. Class 3 Gr. A",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/V-E2HDP.jpg"
            ],
            [
                "name" => "Toshiba CV452J V-E4HDP",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "V-E4HDP",
                "type" => "CV452J",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Toshiba",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "1.0 kVA, 4.2 V pri. / 120 V sec., 50/60 Hz, Ins. Class 1.0 Gr. A",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/V-E4HDP.jpg"
            ],
            [
                "name" => "Transformer Technologies CPT3600341606",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "CPT3600341606",
                "type" => "8110",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Transformer Technologies LTD",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.3 kVA, PRI: 4160V, SEC: 120/240V, 50-60 HZ",
                "additionalKeywords" => "Square D",
                "price" => "* please call or request quote",
                "shippingWeight" => "26 pounds",
                "image" => "img/product/Control Power Transformer/CPT3600341606.jpg"
            ],
            [
                "name" => "Westinghouse LF 2114A96G01",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2114A96G01",
                "type" => "LF",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, 2400 - 120V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/2114A96G01.jpg"
            ],
            [
                "name" => "Westinghouse 351D67G14",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "3351D67G14",
                "type" => "SJA/SJS/SJD/SL",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, 2300V-120V/230V @40Hz",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/3351D67G14.jpg"
            ],
            [
                "name" => "Westinghouse LF50 3405D92G02",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "3405D92G02",
                "type" => "LF50",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, 4160 pri., 120V sec",
                "additionalKeywords" => "2147A11G05, 6406D14G02, HTA67374-001, C7.5E1D1C2, C7.5E1D1F2, MC2147A11G05",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/3405D92G02.jpg"
            ],
            [
                "name" => "Monster Electrical SL MC.C20A1D1C2",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC.C20A1D1C2",
                "type" => "SL",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Monster Electrical",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '2.0kVA, 2400 PRI, 120/240 SEC, Includes 36" High-side/Low-side Lead wires.',
                "additionalKeywords" => "C20A1D1C2, OL-502854.",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/MCC20A1D1C2_front.jpg"
            ],
            [
                "name" => "Monster Electrical SL/SJ MC.C7.5A1D1F2",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC.C7.5A1D1F2",
                "type" => "SL / SJ",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Monster Electrical",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '0.75 kVA, 2400V Pri, 60hZ, 120V Sec., Includes 36" High-side/Low-side Lead wires.',
                "additionalKeywords" => "3405D92G01, 6406D14G01, OL-502830, 339080107",
                "price" => "* please call or request quote",
                "shippingWeight" => "18 pounds",
                "image" => "img/product/Control Power Transformer/MC.C7.5A1D1F2.jpg"
            ],
            [
                "name" => "Westinghouse LF-SJ 6406D14G02",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "6406D14G02",
                "type" => "LF-SJ",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75kVA, 4160V pri., 120V sec., 60Hz., Equivalent to the Cutler-Hammer model #2147A11G05 (0.75kVA) and and SL model #C7-E1D1C2 (0.75kVA).",
                "additionalKeywords" => "CPT, 2147A11G05 (Cutler-Hammer), C7-5E1D1C2 (Cutler-Hammer), 3405D92G02, HTA67374-001, C7.E1D1F2, MC2147A11G05",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/6406D14G02.jpg"
            ],
            [
                "name" => "Westinghouse LF-50 827D994G01",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "827D994G01",
                "type" => "LF-50",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.4 kVA, 2300V-115V, Type :  LFV",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/827D994G01.jpg"
            ],
            [
                "name" => "Monster Electrical MC2147A11G05",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC2147A11G05",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Monster Electrical",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75kVA, PRI:4160V, SEC: 120/240V, 60Hz.",
                "additionalKeywords" => "C7.5E1D1C2 (Cutler-Hammer), HTA67374-001 (Cutler-Hammer), 3405D92G02, 6406D14G02, 2147A11G05",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/MC2147A11G05.jpg"
            ],
            [
                "name" => "General Electric 9T28Y5600",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "9T28Y5600",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "5.0 kVA, 2400V to 120/240V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/9T28Y5600.jpg"
            ],
            [
                "name" => "Westinghouse 479A630G01",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "479A630G01",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3kVA, 4160 PRI., 120/240 SEC.",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "54.4 pounds",
                "image" => "img/product/Control Power Transformer/479A630G01.jpg"
            ],
            [
                "name" => "Siemens CPTAFP13475",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "CPTAFP13475",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, PRI: 4000V, SEC: 115/230VAC",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/CPTAFP13475.jpg"
            ],
            [
                "name" => "Allen Bradley 2563842001 (4002)",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2563842001 (4002)",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.5 kVA, 2400V pri., 120V sec., 60Hz., 1Ø",
                "additionalKeywords" => "6-9544, CPT, 25638-420-01-A, 25638-420-01",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/2563842001__4002_.jpg"
            ],
            [
                "name" => "Instrument Transformers CPTS5-95-15-SD05198",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "CPTS5-95-15-SD05198",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Instrument Transformers",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "15.0 kVA, PRI: 4800V, SEC: 120/240V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "268 pounds",
                "image" => "img/product/Control Power Transformer/CPTS5-95-15-SD05198.jpg"
            ],
            [
                "name" => "Isoreg 410223",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "410223",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Isoreg",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, 4160V-240/120V",
                "additionalKeywords" => "Epoycast",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/410223.jpg"
            ],
            [
                "name" => "Isoreg 410322",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "410322",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Isoreg",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "5.0kVA, 4160pri., 120/240sec.",
                "additionalKeywords" => "Epoycast",
                "price" => "* please call or request quote",
                "shippingWeight" => "150 pounds",
                "image" => "img/product/Control Power Transformer/410322.jpg"
            ],
            [
                "name" => "MC MC12846",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC12846",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "MC",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '0.75 kVA, 4160V, Sec: 120/240V, Includes 36" High-side/Low-side Lead wires.',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/MC12846.jpg"
            ],
            [
                "name" => "MC MC12849",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC12849",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "MC",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, 4160V, Sec: 120/240V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/MC12849.jpg"
            ],
            [
                "name" => "MC MC12850",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC12850",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "MC",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, 4160V, Sec: 120/240V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/MC12850.jpg"
            ],
            [
                "name" => "MC MC12852",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC12852",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "MC",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75 kVA, 2300V, Sec: 120/240V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "23 pounds",
                "image" => "img/product/Control Power Transformer/MC12852.jpg"
            ],
            [
                "name" => "MC MC12855",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC12855",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "MC",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, 2300V, Sec: 120/240V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/MC12855.jpg"
            ],
            [
                "name" => "MC MC12856",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC12856",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "MC",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, 2300V, Sec: 120/240V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/MC12856.jpg"
            ],
            [
                "name" => "Instrument Transformers 3CPT5-95-15-1322A",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "3CPT5-95-15-1322A",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Instrument Transformers",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "15.0 kVA, PRI V L/L: 13200V, Delta SEC: 208Y-120V. Dry-Type :  Transformer.",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "650 pounds",
                "image" => "img/product/Control Power Transformer/3CPT5-95-15-1322A.jpg"
            ],
            [
                "name" => "AFP 10766",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "10766",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "AFP",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0 kVA, 4160V pri., 115/230V sec., 50/60Hz. (IC) Insul.Class 200 C, Temp. Rise 115 C",
                "additionalKeywords" => "9T24Y289, 10766, 573A350P45",
                "price" => "* please call or request quote",
                "shippingWeight" => "62 pounds",
                "image" => "img/product/Control Power Transformer/10766.jpg"
            ],
            [
                "name" => "AFP 573A350P86",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "573A350P86",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "AFP",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => ".75Kva, 2.4kVpri, 115/230Vsec. 50/60hZ",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/573A350P86_front.jpg"
            ],
            [
                "name" => "ABB CPTA6052400D148",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "CPTA6052400D148",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "ABB",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "5.0kVA, PRI: 2400V, SEC: 120-240V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "165 pounds",
                "image" => "img/product/Control Power Transformer/CPTA-60-5-2400-D148.jpg"
            ],
            [
                "name" => "ABB CPTA951513800D149",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "CPTA951513800D149",
                "type" => "Transformer",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "ABB",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "15kVA 13.8kVA/120-240V Dry",
                "additionalKeywords" => "Dry Type :  Transformer CPT-1K",
                "price" => "* please call or request quote",
                "shippingWeight" => "285 pounds",
                "image" => "img/product/Control Power Transformer/CPTA951513800D149.jpg"
            ],
            [
                "name" => "AFP 10690",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "10690",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "AFP",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0kVA, 2300V, 115/230V, 1 Phase, 60Hz.",
                "additionalKeywords" => "573A350P54",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/10690_front.jpg"
            ],
            [
                "name" => "AFP 10691",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "10691",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "AFP",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, 4160V, Sec: 115/230V",
                "additionalKeywords" => "8700106910, 573A350P53",
                "price" => "* please call or request quote",
                "shippingWeight" => "68 pounds",
                "image" => "img/product/Control Power Transformer/10691.jpg"
            ],
            [
                "name" => "General Electric IC-2812 9T24Y209G7",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "9T24Y209G7",
                "type" => "IC-2812",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 KVA, Pri. 2300V, Sec. 230V",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/General electric IC 2812.jpg"
            ],
            [
                "name" => "General Electric CR193 9T24Y289",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "9T24Y289",
                "type" => "CR193",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "2.0kVA, 4160V pri., 115/230V sec., 50/60Hz. Approx. % IMP =3.6, REF 573A350P45",
                "additionalKeywords" => "CPT, 573A350P45, 10766",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/9T24Y289.jpg"
            ],
            [
                "name" => "General Electric IC-302/IC-2814 9T28B9703G14",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "9T28B9703G14",
                "type" => "IC-302 / IC-2814",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, 4160V pri., 115/230V sec., 60Hz.",
                "additionalKeywords" => "CPT",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/9T28B9703G14.jpg"
            ],
            [
                "name" => "Cutler-Hammer LF-SJ 2147A11G05",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2147A11G05",
                "type" => "LF-SJ",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75kVA, 4160V pri., 115V sec., 60Hz.",
                "additionalKeywords" => "CPT, C7.5E1D1C2 (Cutler-Hammer), HTA67374-001 (Cutler-Hammer), 3405D92G02, 6406D14G02",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/2147A11G05.jpg"
            ],
            [
                "name" => "Monster Electrical SJ MC.3351D67G03",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "MC.3351D67G03",
                "type" => "SJ",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Monster Electrical",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '2.0kVA, 4160 pri, 120/240 sec., 60Hz, 150° C Rise, Single Phase, Step Down Dry Type : , Includes 36" High-side/Low-side Lead wires.',
                "additionalKeywords" => "3351D67G03, Q37214",
                "price" => "* please call or request quote",
                "shippingWeight" => "33lbs pounds",
                "image" => "img/product/Control Power Transformer/MC.3351D67G03.jpg"
            ],
            [
                "name" => "Siemens 97H35 25-213-133-001",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "25-213-133-001",
                "type" => "97H35",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Siemens",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "0.75kVA, 2300VAC-115VAC",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Control Power Transformer/25-213-133-001.jpg"
            ],
            [
                "name" => "AFP 8700106910M",
                "category" => "ControlPower",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "8700106910M",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "AFP",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "3.0 kVA, 4160V, 115/230V, 1 Phase, 60Hz",
                "additionalKeywords" => "573A350P53",
                "price" => "* please call or request quote",
                "shippingWeight" => "61 pounds",
                "image" => "img/product/Control Power Transformer/8700106910M.jpg"
            ],
        ]);
    }
}
