<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class equipmentDetail extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('product')->insert([
            [
                "name" => "Cutler-Hammer MEGA 3  2109A25G01",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2109A25G01",
                "type" => "MEGA 3",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "",
                "additionalKeywords" => "
                kV Nom.	5. Poles 3. 3Ø Reactor, LRA 301-480, 4 Taps Each Phase: 0, 1, 2, 3, 4000-4160V. 424 HP
                ",
                "price" => "* please call or request quote",
                "shippingWeight" => "702 pounds",
                "image" => "img/product/Equipment/Cutler Hammer/2109A25G01.jpg"
            ],
            [
                "name" => "Cutler-Hammer Exciter C30E5K1D6",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "C30E5K1D6",
                "type" => "Exciter",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Poles 3. 3Ø Exciter",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "80 pounds",
                "image" => "img/product/Equipment/Cutler Hammer/C30E5K1D6_Mega_3.jpg"
            ],
            [
                "name" => "Cutler-Hammer 2147A21G35",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2147A21G35",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Poles 3. Insulated Main Buss Support Kit, Includes: Insulated Main Buss Support 2147A21G36, Insulated Main Buss Clamp 2147A21G38, and Hardware",
                "additionalKeywords" => "2147A21G36, 2147A21G38, Main Insulated Bus Support Kit",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Cutler Hammer/2147A21G35.jpg"
            ],
            [
                "name" => "Cutler-Hammer 2147A21G37",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2147A21G37",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => 'Poles 3. Non-Insulated Main Buss Support, LOA 19½"',
                "additionalKeywords" => "6445D54",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Cutler Hammer/2147A21G37.jpg"
            ],
            [
                "name" => "Cutler-Hammer Load WFS-9078A40G16",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "WFS-9078A40G16",
                "type" => "Load Interrupter",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "600",
                "controlVoltage" => "",
                "desc" => "kV Nom. 15. kV Max. 15. kV BIL 95.Poles 3. AIC 40000. Load Interrupter Switch",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Cutler Hammer/WFS-9078A40G16-062113.jpg"
            ],
            [
                "name" => "Cutler-Hammer Versa-Rupter 244043507",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "244043507",
                "type" => "Versa-Rupter",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "600",
                "controlVoltage" => "",
                "desc" => "kV Nom. 27. kV Max.	27. Poles 3.AIC 40000. Non-fused",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Cutler Hammer/244043507-050709.jpg"
            ],
            [
                "name" => "Cutler-Hammer 2147A21G38",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2147A21G38",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Poles 3. Insulated Main Buss Clamp",
                "additionalKeywords" => "6445D53",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Cutler Hammer/Cutler Hammer 2147A21G38 (1).jpg"
            ],
            [
                "name" => "Cutler-Hammer 2147A21G36",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2147A21G36",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => 'Poles 3. Insulated Main Buss Support, LOA 19½"',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Cutler Hammer/2147A21G36.jpg"
            ],
            [
                "name" => "IC1074A106C",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "IC1074A106C",
                "type" => "IC1074A106C",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "600",
                "controlVoltage" => "",
                "desc" => "kV Nom. 4.16. kV Max. 5kV BIL 60. Poles 3. 3-pole unit. Momentaru & Fault Close RMS 61,000 Amps",
                "additionalKeywords" => "Cat# 0643X0292Q01-A01, GEH-3091 426B, Diagram 335B1464 SH.3",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC1074B201C",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "IC1074B201C",
                "type" => "IC1074B201C",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "600",
                "controlVoltage" => "",
                "desc" => "kV Nom.	2400. kV Max. 5. kV BIL	60. Poles 3. AIC 61000.",
                "additionalKeywords" => "0522X0955V01C01",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SE-100S",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "SE-100S",
                "type" => "0213X0300G3",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "600",
                "controlVoltage" => "",
                "desc" => "kV Nom. 13.2. kV Max. 15.5. kV BIL 95. Poles	3. GE Load-Break Interrupter Switch",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/General Electrric/SE-100S-081216-3.jpg"
            ],
            [
                "name" => "Powercon PIF - PIF 502-209",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "PIF 502-209",
                "type" => "PIF",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Powercon",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => "kV Nom. 4.16. kV Max. 4.76. kV BIL 60. Poles	3. 22.5 K Amps Asym. Mom., 22.5 K Amps Asym. Fault Close, 105# Nom.",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Powercon/PIF_502-209.jpg"
            ],
            [
                "name" => "Powercon Load Break PIF-A67-19",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "PIF-A67-19",
                "type" => "Load Break Interupter",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Powercon",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "1200",
                "controlVoltage" => "",
                "desc" => "kV Nom. 5. kV Max. 7.2. kV BIL 60. Poles 3. 5.0kV, 60Hz, 3Ø, 40K Amps Asym. Mom., 61K Amps Asym. Fault Close",
                "additionalKeywords" => "25-324-375-501",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Powercon/PIF-A67-19-031616-1_front.jpg"
            ],
            [
                "name" => "S&C Mini-Rupter 255232",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "255232",
                "type" => "Mini-Rupter",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "S&C",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "600",
                "controlVoltage" => "",
                "desc" => "kV Nom. 14.4. kV Max. 17. kV BIL	95. Poles 3. Frame not Included: Rocker Arm, Handle, Arc Chutes removed from Frame. Details Frame",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/S&C/255232-062117.jpg"
            ],
            [
                "name" => "S&C Interrupter SA-30818R4",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "SA-30818R4",
                "type" => "S and C Interrupter",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "S&C",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "1200",
                "controlVoltage" => "",
                "desc" => "Poles 1. Interrupter and Load Terminal for XL and NL Regulator Bypass Switch 14.4kV-25kV, Outdoor",
                "additionalKeywords" => "S&C",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/S&C/S_C_Interrupter.jpg"
            ],
            [
                "name" => "Square D HMVR - HMVR-30500-U",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "HMVR-30500-U",
                "type" => "HMVR",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Square D",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "200",
                "controlVoltage" => "",
                "desc" => "kV Nom. 5. kV Max. 5. kV BIL	60.Poles 3. AIC 60000. Class 6042",
                "additionalKeywords" => "44070-620-50, HMVX",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Square D/HMVR-30500-U-111909.jpg"
            ],
            [
                "name" => "Square D High Voltage Load HVL031506",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "HVL031506",
                "type" => "High Voltage Load Break",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Square D",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "600",
                "controlVoltage" => "",
                "desc" => "kV Nom. 15. kV Max. 15. kV BIL 95. Poles 3. AIC 61000.",
                "additionalKeywords" => "17-2792429C, J19X0001",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Square D/HVL031506-043009.jpg"
            ],
            [
                "name" => "Square D 44035-183-50",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "44035-183-50",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Square D",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "600",
                "controlVoltage" => "",
                "desc" => "kV Nom. 15. kV Max. 15. kV BIL 95. Poles 3. 60Hz, Sw.MOM.Rating 61,000A.Asy, Intigrated Sw. & Fuse Short Circuit Rating 40,000 A.Asy, Fuses RBA-400/150E.",
                "additionalKeywords" => "L10U0001",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Square D/44035-183-50-111312-1.jpg"
            ],
            [
                "name" => "Westing house ADM Verticle 6391D55G01",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "6391D55G01",
                "type" => "ADM Verticle Fuse Puller",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => 'Verticle Fuse Puller for ADM Disconnect Switch, L.O.A. 27½"',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Westinghouse/Westing house ADM verticle 6391D55G01 (1).jpg"
            ],
            [
                "name" => "Westing house ADM 6391D55G02",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "6391D55G02",
                "type" => "ADM Horizontal Fuse Puller",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => 'Horizontal Fuse Puller for ADM Disconnect Switch, L.O.A. 27-7/8"',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Westinghouse/6391D55G02.jpg"
            ],
            [
                "name" => "Westing house ADM - ADM",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "ADM",
                "type" => "ADM",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "600",
                "controlVoltage" => "",
                "desc" => "kV Nom. 5.5. kV Max. 5.5. kV BIL 60. Poles 3. AIC 60000. Lower, Horizontal Fuse Mount",
                "additionalKeywords" => "3497C, 6386D30, 2147A02G07 (oper. mech.), 2147A02G05 (main spring, rod, mounting), 2147A02G09 (shaft w/ rod ends), 2147A02G12 (latch lever mech.)",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Westinghouse/ADM-092413-2.jpg"
            ],
            [
                "name" => "Westing house ADM Flicker Blade",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "Flicker Blade",
                "type" => "ADM",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Flicker Blade for ADM Disconnect Switch, Part of Flicker Blade Assembly 2147A02G06",
                "additionalKeywords" => "2147A02G06, Whip",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Westinghouse/Flicker_Blade.jpg"
            ],
            [
                "name" => "AFP Autotransformer 10416",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "10416",
                "type" => "Autotransformer",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "AFP",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "kV Nom. 4.16. Poles 3. Pri. 4160V, Sec. 50%, 65%, 80%, 400HP, 3Ø, 60Hz, Temp. Rise 80 C, 58.3 FLA, 350 LRA, Insulation Class B",
                "additionalKeywords" => "25-154-452-002",
                "price" => "* please call or request quote",
                "shippingWeight" => "510 pounds",
                "image" => "img/product/Equipment/Others/10416.jpg"
            ],
            [
                "name" => "Cutler-Hammer MEGA 3 2109A25G01",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2109A25G01",
                "type" => "MEGA 3",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "kV Nom. 5. Poles 3. 3Ø Reactor, LRA 301-480, 4 Taps Each Phase: 0, 1, 2, 3, 4000-4160V. 424 HP",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "702 pounds",
                "image" => "img/product/Equipment/Others/2109A25G01.jpg"
            ],
            [
                "name" => "Cutler-Hammer Exciter C30E5K1D6",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "C30E5K1D6",
                "type" => "Exciter",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Poles 3. 3Ø Exciter",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "80 pounds",
                "image" => "img/product/Equipment/Others/C30E5K1D6_Mega_3.jpg"
            ],
            [
                "name" => "Field Transformers 7196",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "7196",
                "type" => "Autotransformer",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Field Transformers",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "kV Nom. 4.16. Poles 3. Pri. 4160V, Sec. 50%, 65%, 80%, 1750HP, 3Ø, 60Hz",
                "additionalKeywords" => "Metex",
                "price" => "* please call or request quote",
                "shippingWeight" => "1540 pounds",
                "image" => "img/product/Equipment/Others/7196.jpg"
            ],
            [
                "name" => "Field Transformers 8494",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "8494",
                "type" => "Transformer",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Field Transformers",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "kV Nom. 4.16. Poles 3. 12kVA, 4160 Pri., 480 Sec., 60Hz.",
                "additionalKeywords" => "Metex",
                "price" => "* please call or request quote",
                "shippingWeight" => "198 pounds",
                "image" => "img/product/Equipment/Others/8494.jpg"
            ],
            [
                "name" => "Hammond J 188986",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "188986",
                "type" => "J",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Hammond",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "kV Nom. 4.16. kV Max. 4.16. kV BIL 30. Poles 3. HP 900, %taps 50-65-80, FLA 126, LRA 754, Temp Class 220, 60 Hz, NEMA Medium Duty",
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "874 pounds",
                "image" => "img/product/Equipment/Others/188986.jpg"
            ],
            [
                "name" => "Hammond J 2823N9.0P",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2823N9.0P",
                "type" => "J",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Hammond",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "kV Nom. 4.16. kV Max. 4.16. kV BIL 30. Poles 3. HP 900, %taps 50-65-80, FLA 126, LRA 754, Temp Class 220, 60 Hz, NEMA Medium Duty",
                "additionalKeywords" => "2823N9.OP",
                "price" => "* please call or request quote",
                "shippingWeight" => "880 pounds",
                "image" => "img/product/Equipment/Others/2823N9.0P.jpg"
            ],
            [
                "name" => "Westinghouse ADM Verticle 6391D55G01",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "6391D55G01",
                "type" => "ADM Verticle Fuse Puller",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => 'Verticle Fuse Puller for ADM Disconnect Switch, L.O.A. 27½"',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Westinghouse/Westing house ADM verticle 6391D55G01 (1).jpg"
            ],
            [
                "name" => "Westinghouse ADM 6391D55G02",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "6391D55G02",
                "type" => "ADM Horizontal Fuse Puller",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => 'Horizontal Fuse Puller for ADM Disconnect Switch, L.O.A. 27-7/8"',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Others/6391D55G02.jpg"
            ],
            [
                "name" => "Westinghouse ADM Flicker Blade",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "Flicker Blade",
                "type" => "ADM",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Flicker Blade for ADM Disconnect Switch, Part of Flicker Blade Assembly 2147A02G06",
                "additionalKeywords" => "2147A02G06, Whip",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Others/Flicker_Blade.jpg"
            ],
            [
                "name" => "Hammond 6829N44.1F",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "6829N44.1F",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Hammond",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Poles 3. 3 Phase Reactor, 4410KVAR, 4160 Volt, 60Hz, 612 LRA, 102 FLA, 0-50-65-80-100% Taps, NEMA Med Duty, Cat# 6829N44.1F, S/N 7329M93 51175-044-82",
                "additionalKeywords" => "51175-044-82",
                "price" => "* please call or request quote",
                "shippingWeight" => "1005 pounds",
                "image" => "img/product/Equipment/Others/6829N44.1F.jpg"
            ],
            [
                "name" => "Cutler-Hammer 2147A21G37",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2147A21G37",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => 'Poles 3. Non-Insulated Main Buss Support, LOA 19½"',
                "additionalKeywords" => "6445D54",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Others/2147A21G37.jpg"
            ],
            [
                "name" => "Hammond 2729N7.9F",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2729N7.9F",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Hammond",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Poles 3. 3 Phase Auto Transformer, 4160 Volt, 60Hz, 608 LRA, 122 FLA, 50-65-80 %Taps, NEMA Med Duty, S/N 6758H93 25-154-456-080 1.15 SF 790KW",
                "additionalKeywords" => "25-154-456-080",
                "price" => "* please call or request quote",
                "shippingWeight" => "910 pounds",
                "image" => "img/product/Equipment/Others/2729N7.9F.jpg"
            ],
            [
                "name" => "Cutler-Hammer 2147A21G35",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2147A21G35",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Poles 3. Insulated Main Buss Support Kit, Includes: Insulated Main Buss Support 2147A21G36, Insulated Main Buss Clamp 2147A21G38, and Hardware",
                "additionalKeywords" => "2147A21G36, 2147A21G38, Main Insulated Bus Support Kit",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Others/2147A21G35.jpg"
            ],
            [
                "name" => "Cutler-Hammer 2147A21G36",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2147A21G36",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => 'Poles 3. Insulated Main Buss Support, LOA 19½"',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Others/2147A21G36.jpg"
            ],
            [
                "name" => "Cutler-Hammer 2147A21G38",
                "category" => "Equipment",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "2147A21G38",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "Poles 3. Insulated Main Buss Clamp",
                "additionalKeywords" => "6445D53",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Equipment/Cutler Hammer/Cutler Hammer 2147A21G38 (1).jpg"
            ],
        ]);
    }
}
