<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class isolationSwitchesDetail extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('product')->insert([
            [
                "name" => "Allen Bradley - 1152 Model - 360 Amp - 4600 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "1152",
                "partNo" => "1152 Air Isolation Switch",
                "type" => "1152",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "4600",
                "amps" => "360",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Isolation Switches/Allen Bradley/Allen_Bradley-1152.jpg"
            ],
            [
                "name" => "Allen Bradley - 1502V4 Model - 400 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "1502V4",
                "partNo" => "1502V4-Isolation Switch",
                "type" => "1502 Vacuum",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => '400A w/Fuse Clips',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Isolation Switches/Allen Bradley/1502V4-Isolation_Switch.jpg"
            ],
            [
                "name" => "Allen Bradley - Vacuum Model - 800 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "Vacuum",
                "partNo" => "1502V8 Isolation Switch",
                "type" => "1502 Vacuum",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "800",
                "controlVoltage" => "",
                "desc" => '800A Bolt-in Fuse Style',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Isolation Switches/Allen Bradley/Allen bradley vacuum 800-5000.jpg"
            ],
            [
                "name" => "Allen Bradley - 1502 Model - 800 Amp Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "1502",
                "partNo" => "1503-HM2",
                "type" => "1502 Vacuum",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "",
                "amps" => "800",
                "controlVoltage" => "",
                "desc" => 'Isolation Switch Handle Module, 600A & 800A W/ Hardware',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Isolation Switches/Allen Bradley/1503-HM2.jpg"
            ],
            [
                "name" => "Allen Bradley - 1503S Model - 400 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "1503S",
                "partNo" => "1503S-4C",
                "type" => "1502 Vacuum",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "AB Receiver Assembly",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Isolation Switches/Allen Bradley/1503S-4C-033019-4_front.jpg"
            ],
            [
                "name" => "Cutler-Hammer - 7864A50G01 Model - 830 Amp - 7200 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "7864A50G01",
                "partNo" => "LFM-8",
                "type" => "SJA",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "7200",
                "amps" => "830",
                "controlVoltage" => "",
                "desc" => 'Vacuum Contactor Model',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Isolation Switches/C-H,Eaton/LFM-8-041521-01_front.jpg"
            ],
            [
                "name" => "Cutler-Hammer - 2085A72G15 Model - 360 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "2085A72G15",
                "partNo" => "50LFR-4 (2085A72G15)",
                "type" => "LF-50",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "",
                "desc" => '17 1/2" Tall Iso. Switch',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "62lbs pounds",
                "image" => "img/product/Isolation Switches/C-H,Eaton/50LFR-4__2085A72G30_.jpg"
            ],
            [
                "name" => "Square D - 8198 Model - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "8198",
                "partNo" => "Square D 8198 Isolation Switch",
                "type" => "8110",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Square D",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => 'w/Buss',
                "additionalKeywords" => "Iso-Flex",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Isolation Switches/Square D/Square_D_8198_Isolation_Switch.jpg"
            ],
            [
                "name" => "Square D - 360 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "8110-Vacuum Isolation Switch",
                "type" => "8110 Vacuum",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Square D",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "",
                "desc" => 'Fixed isolation switch from an Isoflex 8198 vacuum starter. Accompanies 8110-V2540 and 8110-V3540 contactors',
                "additionalKeywords" => "51190, 8198",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "General Electric - CR194 Isolation Switch Model - 400 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "CR194 Isolation Switch",
                "partNo" => "55C682220G1",
                "type" => "CR193",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => '26" QMQB, Interlocking Mechanism, Handle Assembly for CR194 One High Vacuum Limitamp Controller.',
                "additionalKeywords" => "	55D781326G1, 55D781301G2, 55B533212G4",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Isolation Switches/General Electric/CR194_Isolation_Switch.jpg"
            ],
            [
                "name" => "General Electric - CR194 Isolation Switch Model - 400 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "CR194 Isolation Switch",
                "partNo" => "55C682220G2",
                "type" => "CR193",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => '34" QMQB, Interlocking Mechanism, Handle Assembly for CR194 One High Vacuum Limitamp Controller.',
                "additionalKeywords" => "QMQB, 55C682220G1, 109W8268P001",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Isolation Switches/General Electric/55C682220G2.jpg"
            ],
            [
                "name" => "General Electric - CR194 Isolation Switch Model - 725 Amp - 4160 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "CR194 Isolation Switch",
                "partNo" => "55C682236G1",
                "type" => "CR193C",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "4160",
                "amps" => "725",
                "controlVoltage" => "",
                "desc" => '800A CONT - SW ROD ASM. Incudes- Brain Box, 2 Aux. Contacts.',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "10 pounds",
                "image" => "img/product/Isolation Switches/General Electric/55C682236G1.jpg"
            ],
            [
                "name" => "General Electric - CR194 Isolation Switch Model - 725 Amp - 4160 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "CR194 Isolation Switch",
                "partNo" => "55D781309G11",
                "type" => "CR193C",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "4160",
                "amps" => "725",
                "controlVoltage" => "",
                "desc" => '800a Isolation Switch (QMQB), Interlocking Mechanism, Handle Assembly for CR194 One High Vacuum Limitamp Controller',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "175 pounds",
                "image" => "img/product/Isolation Switches/General Electric/55D781309G11.jpg"
            ],
            [
                "name" => "Westinghouse - 2085A70G10 Model - 200 Amp - 2500 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "2085A70G10",
                "partNo" => "25LFM-2",
                "type" => "LF-25",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "2500",
                "amps" => "200",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Westinghouse - Canadian Model - 360 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "Canadian",
                "partNo" => "50LFM-4 (Canadian)",
                "type" => "LF-50",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "",
                "desc" => "Alternate Handle & Front Plate Ass'y",
                "additionalKeywords" => "3549C03H02, 112D689G02, LFR, LFS, LFM",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Westinghouse - 50LFM-4(D) Model - 360 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "50LFM-4(D)",
                "partNo" => "50LFM-4 (D)",
                "type" => "LF50",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "",
                "desc" => 'LF50 AIR w/Dbl Fuse Clips. 18 1/2"T. 15 1/2"W.',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "75 pounds",
                "image" => ""
            ],
            [
                "name" => "Westinghouse - LFM50 Model - 200 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "LFM50",
                "partNo" => "LFM50L2",
                "type" => "LF-50",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "5000",
                "amps" => "200",
                "controlVoltage" => "",
                "desc" => 'Obsolete. 25LFM-2 Compatable.
                Additional Keywords : 	Obsolete style series = 447A546.',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Westinghouse - 2085A72G30 Model - 360 Amp - 5000 Volt Isolationswitch",
                "category" => "IsolationSwitch",
                "partModelNo" => "",
                "modelNo" => "2085A72G30",
                "partNo" => "50LFR-4 (2085A72G30)",
                "type" => "SJA",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "",
                "desc" => 'Single Fuse Clamps, w/ 2 Micro Switches',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
        ]);
    }
}
