<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class productSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('product')->insert([
            [
                "name" => "1502 vacuum - 400 amp",
                "category" => "Contractors",
                "partModelNo" => "1502-V4C1D1",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502 Vacuum",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => 'Series "A"',
                "additionalKeywords" => "VZ4-PE-C 5000, 1502-V4C1D1",
                "price" => "* please call or request quote",
                "shippingWeight" => "46 pounds",
                "image" => "img/product/Contactors/1502V4C1D1-032214-1.jpg"
            ],
            [
                "name" => "1502 vacuum - 400 amp, Gray-plastic",
                "category" => "Contractors",
                "partModelNo" => "(1502-V4CBD-1) / (1502-V4DBDA-1) / (1502-VC4DBDB-0) / (1502-V4CCD-1)",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502 Vacuum",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "(2400 / 5000) - (2500/7200) - (2500/5000)",
                "amps" => "360 - 400",
                "controlVoltage" => "120 AC",
                "desc" => '',
                "additionalKeywords" => "1502-V4CBD1-1",
                "price" => "* please call or request quote",
                "shippingWeight" => "46 pounds",
                "image" => "img/product/Contactors/1502-V4CBD1-110315.jpg"
            ],
            [
                "name" => "1502 vacuum - 450 amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => "",
                "additionalKeywords" => "",
                "price" => "",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "1502 vacuum - 800 amp",
                "category" => "Contractors",
                "partModelNo" => "(1502-VC8DXDA-1) / (1502-V8DXDA-1)",
                "modelNo" => "Series E",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502 Vacuum",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "2500 / 7200",
                "amps" => "800",
                "controlVoltage" => "",
                "desc" => "3Ø, 50/60Hz, Interrupting Capacity 12000Amp., Altitude 0-1000M",
                "additionalKeywords" => "Rockwell Automation",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/1502-V8DXD-1-072312-1.jpg"
            ],
            [
                "name" => "1502 vacuum - 800 amp",
                "category" => "Contractors",
                "partModelNo" => "1502-V8C6D1",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502 Vacuum",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "2500 / 7200",
                "amps" => "800",
                "controlVoltage" => "",
                "desc" => 'Series A, 3 φ, Interrupting Rate: 11',
                "additionalKeywords" => "VZ8-PE-C",
                "price" => "* please call or request quote",
                "shippingWeight" => "122 pounds",
                "image" => "img/product/Contactors/1502-V8C6D1-110315-2.jpg"
            ],
            [
                "name" => "Allen Bradley 1500 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "1502 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "(1502-A4C3D1) / (1502-A4C3D3)",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "5000 / 2500",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "Centerline, 1502A4C3D1",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/1502A4C3D1-020509-2.jpg"
            ],
            [
                "name" => "Allen Bradley - 1502 -800 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "A",
                "partNo" => "1502-A8C4D3",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "800",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Allen Bradley - 1152 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Allis Chalmers - 25-118-537-501 Model - 400 Amp - 5000 / 2500 Volt Contactor",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "25-118-537-501",
                "partNo" => "456-D (black plastic arch chute)",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "456-D (Black Plastic Arch Chute)",
                "brandName" => "Allis Chalmers",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000 / 2500",
                "amps" => "400",
                "controlVoltage" => "230 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Allis Chalmers - 14-514-449 Model - 400 Amp - 5000 / 2500 Volt Contactor",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "14-514-449",
                "partNo" => "456-D (older gray arch chute)",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "456-D",
                "brandName" => "Allis Chalmers",
                "vacuumAir" => "",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000 / 2500",
                "amps" => "400",
                "controlVoltage" => "90 DC",
                "desc" => '0.75kVA, w/ 2 Barrel Fuse Clips',
                "additionalKeywords" => "456D, 2-4470-4224-1, 14-514-449, 456D",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Allis Chalmers - 256-1 Model - 200 Amp - 5000 Volt Contactor",
                "category" => "Contractors",
                "partModelNo" => "256-1",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "256-1",
                "brandName" => "Allis Chalmers",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "200",
                "controlVoltage" => "",
                "desc" => 'Obsolete',
                "additionalKeywords" => "256",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/256-1.jpg"
            ],
            [
                "name" => "SL-50 - (200-400 Amp)",
                "category" => "Contractors",
                "partModelNo" => "(SL50W430)/(SL50F230)/(SL50F430)/(SL50W230)/(SL50W430B)",
                "modelNo" => "A / B",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SL-50",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In / Slide-In",
                "primaryVoltage" => "2400 / 7200 - 4160",
                "amps" => "200 - 400",
                "controlVoltage" => "120 AC",
                "desc" => '3Ø, 60Hz, BIL 60kV, Control VA Inrush 600 Seal 30, Max. Intrptg Capacity 8500 A, Dropout Time 250 mSec, Altitude -1000m to +2000m, G.O. HUDT55275-001',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "112 pounds",
                "image" => "img/product/Contactors/SL50W430B-101910-1.jpg"
            ],
            [
                "name" => "SL-72 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "(SL72S) / (SL72B)",
                "modelNo" => "A",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SL72S4",
                "brandName" => "Eaton",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "4160",
                "amps" => "400",
                "controlVoltage" => "120 AC",
                "desc" => 'Dropout Time 130 mSec, 3Ø, 60kV BIL, Control VA Inrush 1000 Seal 40',
                "additionalKeywords" => "SL72S4H3L",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/SL72S-090216-2_back (1).jpg"
            ],
            [
                "name" => "SLN - (200-400 Amp)",
                "category" => "Contractors",
                "partModelNo" => "(SLN011S5A-220)/(SLN014S7A-550)",
                "modelNo" => "B",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SLN",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '7.2Kv 160A VACUUM CONTACTOR',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/SLN014S7A-550-062415-2.jpg"
            ],
            [
                "name" => "SJA-25 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "VMAN3FN4A1-T1",
                "partNo" => "SJA25VW430",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SJA-25",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2500",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => 'Model C, 3Ø, 60Hz',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/SJA25VW430-110315-2.jpg"
            ],
            [
                "name" => "SJA-50 (360-400 Amp)",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "VMAN3FN4E1-TX",
                "partNo" => "SJA50",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SJA-50",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/SJA50VW430-070714-2.jpg"
            ],
            [
                "name" => "SJA-25 - 720 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SJO / SJ-720 - 720 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "9088A08V02",
                "partNo" => "SJ072VW830",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SJ-720",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "7200 / 2600",
                "amps" => "720",
                "controlVoltage" => "220 / 240 AC",
                "desc" => '800 Amp, The Cutler-Hammer SJ vacuum model replaces the Westinghouse LF air break model. PN: 9088A08V02',
                "additionalKeywords" => "SJO72VW830, 9910D55 (vacuum bottle), (Vac Bottle W/Assembly), 2147A88G12",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/SJO72VW830-042709-1.jpg"
            ],
            [
                "name" => "SJS-50 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "1A48747G01",
                "partNo" => "SJS50VW430",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SJS-50",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => '',
                "additionalKeywords" => "2147A45G21, 2147A45G22, 2147A45G23, 2147A45G24, 5259C33 (vacuum bottle), SJS50VW430",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/SJS50VW430-112911-23.jpg"
            ],
            [
                "name" => "9950 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "VMAN3FN4A1-T1",
                "partNo" => "SJA25VW430",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SJA-25",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2500",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => 'Model C, 3Ø, 60Hz',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/SJA25VW430-110315-2.jpg"
            ],
            [
                "name" => "C80 - 1350 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "CR193B - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "(CR193B)/(CR193)",
                "modelNo" => "CR193B110L001022R",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CR193B",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "7200 / 2300",
                "amps" => "400",
                "controlVoltage" => "120 AC / 115 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CR193-091914-9.jpg"
            ],
            [
                "name" => "CR193C - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "CR193C110L005050U",
                "partNo" => "CR193C",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CR193C",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "800",
                "controlVoltage" => "115 DC",
                "desc" => '800A, 5000V, VACUUM CONTACTOR',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CR193C-062113-1.jpg"
            ],
            [
                "name" => "CR193D - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "CR193D110L005050R",
                "partNo" => "CR193D",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CR193D",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "115 DC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CR193D-111114-4.jpg"
            ],
            [
                "name" => "CR193V - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "(CR193V)/(CR193VC4)/(CR193VB)",
                "modelNo" => "VC4AB3A413AAB/VB4AB2A412AA02A",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CR193VC",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => 'Limitamp Vacuum Conversion',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CR193VB-020414-1.jpg"
            ],
            [
                "name" => "CR193WB - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC-302 - 400 Amp,Wheels",
                "category" => "Contractors",
                "partModelNo" => "(IC302AA4)/(IC-302AB4)/(IC-302AC4)/(IC-302BB4)/(IC-302CB4)/(IC-302EAA4AA1A47AA2A)",
                "modelNo" => "IC302AA4AA3A02AA2A / IC302AB4AB3A47AA28 / IC302AC4AC2A02AA2A / IC302BB4AB2A312AA2A / IC302CB4AB2A02CA2A",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC302A",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In /Roll-In",
                "primaryVoltage" => "5000 / 2300 / 4800",
                "amps" => "400",
                "controlVoltage" => "115 AC / 230 AC / 76DC",
                "desc" => '',
                "additionalKeywords" => "0528X0534R02SA01, IC302A, IC302AA4",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/IC-302CB4-121708-1.jpg"
            ],
            [
                "name" => "IC-302 - 700 Amp",
                "category" => "Contractors",
                "partModelNo" => "(IC302)/(	IC302EC7)/(IC302EB7)",
                "modelNo" => "IC302AA4AA3A02AA2A",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC-302A",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "2300 / 5000",
                "amps" => "400",
                "controlVoltage" => "115 AC / 115 DC",
                "desc" => '',
                "additionalKeywords" => "0482X0176R01-A02",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/IC-302AA4-021913-1.jpg"
            ],
            [
                "name" => "IC-302 - 400 Amp,Slider",
                "category" => "Contractors",
                "partModelNo" => "(IC302)/(IC302B)",
                "modelNo" => "IC302AA4AA3A02AA2A",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC-302A",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "2300 / 2400",
                "amps" => "400",
                "controlVoltage" => "115 AC / 230AC",
                "desc" => '',
                "additionalKeywords" => "0482X0176R01-A02",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/IC-302CB4-121708-1 slider.jpg"
            ],
            [
                "name" => "IC-2814-2 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "IC2814E210B47",
                "partNo" => "IC2814E210",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC-2812-E",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "2400",
                "amps" => "400",
                "controlVoltage" => "230 AC",
                "desc" => 'Includes: Grounding bars',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/IC-2814245A-011209-1.jpg"
            ],
            [
                "name" => "IC-2814 - 700 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC-2812-E - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "(IC-2812E100)/(IC2812E)/(IC-2812E100B)",
                "modelNo" => "IC-2812-E100DA47",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC-2812-E",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "230 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/IC2812E-052914-2.jpg"
            ],
            [
                "name" => "IC-2814-E - (200-400 Amp)",
                "category" => "Contractors",
                "partModelNo" => "(IC2814E)/(IC2814E150)/(IC2814E22)/(IC2814E230B2)/(IC2814E621)/(IC2814220E)/(IC-2814E120AC)/(IC2814E210B)/(IC2814E220)/(IC2814E220B)/(IC2814E220C)/(IC2814E221B)/(IC2814E221C)/IC2814E230B)/(IC-2814E230B)/(IC2814E230C)/(IC-2814E230C)/(IC2814E230EB47A2)/(IC-2814E231B)/(IC2814E231C)/(IC-2814E231E)/(IC-2814E620B)",
                "modelNo" => "IC2814E220B22",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC2814-E",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-in",
                "primaryVoltage" => "4160",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/IC2814E210-121415-1.jpg"
            ],
            [
                "name" => "7840 Vacuum - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "7850 Air - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U032A50-76 - 200 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U034A50-125 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U034A50-76 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "MVC77U034A50-76",
                "partNo" => "MVC77U034A50-76",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "MVC77",
                "brandName" => "Joslyn Clark",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "120 AC",
                "desc" => '400A, 5kVA, COIL 120vAC',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/MVC77U035A50-76.jpg"
            ],
            [
                "name" => "MVC77U034A72-76 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U035A50-76 - 500 Amp",
                "category" => "Contractors",
                "partModelNo" => "MVC77U035A50-76",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "MVC77",
                "brandName" => "Joslyn Clark",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "500",
                "controlVoltage" => "120",
                "desc" => '3Ø, 50/60Hz, Impulse BIL 60kV',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/MVC77U035A50-76.jpg"
            ],
            [
                "name" => "MVC77U036A72-76 - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "VZ2-PE-D - 200 Amp",
                "category" => "Contractors",
                "partModelNo" => "VZ2-PE-D",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "VZ2",
                "brandName" => "Mitsubishi",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "3300 / 6600",
                "amps" => "200",
                "controlVoltage" => "110 / 120",
                "desc" => 'Short Time Current 4kA, Standard NEMA IEC Pub.470, Switching Freq. 600Times/H',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/VZ2-PE-D-072116-1.jpg"
            ],
            [
                "name" => "VZ2-PL-C - 200 Amp",
                "category" => "Contractors",
                "partModelNo" => "VZ2-PL-C",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "VZ2",
                "brandName" => "Mitsubishi",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "4600",
                "amps" => "200",
                "controlVoltage" => "125 DC",
                "desc" => 'Rated Make/Break 35MVA, Short Time Current 4.4kA, Standard NEMA Part ICS 2-234(1978)',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/VZ2-PL-C-060616-1.jpg"
            ],
            [
                "name" => "VZ4-PL-C - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "VZ4-PL-C",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "VZ4",
                "brandName" => "Mitsubishi",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "4600",
                "amps" => "400",
                "controlVoltage" => "125 DC",
                "desc" => 'Rated Make/Break 35MVA, Short Time Current 4.4kA, Standard NEMA Part ICS 2-234(1978)',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/VZ4-PL-C-060616-2.jpg"
            ],
            [
                "name" => "VZ8-PE-D - 800 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "97H35 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "97H3532092A2A",
                "partNo" => "97H35",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "97H35",
                "brandName" => "Siemens",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2300 / 5000",
                "amps" => "360",
                "controlVoltage" => "115 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/97H35-031616-2.jpg"
            ],
            [
                "name" => "94H35 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "94H3533000C0AS",
                "partNo" => "94H35",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "94H35",
                "brandName" => "Siemens",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "125 DC",
                "desc" => '',
                "additionalKeywords" => "25-154-551-556, SVC-93H3",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/94H35-102715-9.jpg"
            ],
            [
                "name" => "93H3 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "SVC93H3",
                "partNo" => "93H3",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "93H3",
                "brandName" => "Siemens",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "",
                "amps" => "400",
                "controlVoltage" => "115 / 120 AC",
                "desc" => '',
                "additionalKeywords" => "CV-5HA, HCV-5HA",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/93H3-041515-3.jpg"
            ],
            [
                "name" => "90H35 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "90H3532002B5AS",
                "partNo" => "90H35",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "90H35",
                "brandName" => "Siemens",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2400 / 5000",
                "amps" => "360",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "25-154-421-532",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/90H35-101912-3.jpg"
            ],
            [
                "name" => "88H35 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "88H3533044A1AT",
                "partNo" => "88H3",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "88H3",
                "brandName" => "Siemens",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2400 / 4800",
                "amps" => "360",
                "controlVoltage" => "115 AC",
                "desc" => '',
                "additionalKeywords" => "25-154-175-566, 88H353",
                "price" => "* please call or request quote",
                "shippingWeight" => "±175 pounds",
                "image" => "img/product/Contactors/88H3-110813-3.jpg"
            ],
            [
                "name" => "3TL8 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "3TL8107-1BA00",
                "partNo" => "3TL8",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "3TL8",
                "brandName" => "Siemens",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "2300",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/3TL8-031616-1.jpg"
            ],
            [
                "name" => "3TL6 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "(3TL6)/(3TL6116-0AK2)",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "3TL6",
                "brandName" => "Siemens",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "2300 / 7200",
                "amps" => "400",
                "controlVoltage" => "115 AC / 120 AC",
                "desc" => '',
                "additionalKeywords" => "3TL6116",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/3TL6-110813-4.jpg"
            ],
            [
                "name" => "81H3 & 81 H2 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "(81H3)/(81H2)",
                "modelNo" => "81H3535064A3",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "81H3",
                "brandName" => "Siemens",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "4800 / 2400 / 5000",
                "amps" => "360 / 180",
                "controlVoltage" => "115 AC",
                "desc" => '',
                "additionalKeywords" => "25-131-813-504, 81H353",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/81H3-021009-10.jpg"
            ],
            [
                "name" => "456-D - 360 Amp, Black plastic arch chuts",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "456-D - 400 Amp, Older gray arch chuts",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "14-514-449",
                "partNo" => "456-D (older gray arch chute)",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "456-D",
                "brandName" => "Allis Chalmers",
                "vacuumAir" => "",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000 / 2500",
                "amps" => "400",
                "controlVoltage" => "90 DC",
                "desc" => '0.75kVA, w/ 2 Barrel Fuse Clips',
                "additionalKeywords" => "456D, 2-4470-4224-1, 14-514-449, 456D",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SL-50 - 200 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SJA-50- 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "8110 Vacuum V3540 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "(8110-3540E),(8110-V3540A),(8110-V3540A-JPDX22-D),(8110V3540E),(8110-V3540E-U3X21-B)",
                "modelNo" => "B",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "8110 Vacuum",
                "brandName" => "Square D",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => '3Ø, 60Hz, Form X11, Max Short CKT CUR 6000Amos @ 5000 Volts',
                "additionalKeywords" => "F.O. 1625018A",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/8110-V3540G-052317-3 (1).jpg"
            ],
            [
                "name" => "8110 Type :  F2 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "51034-060-52",
                "partNo" => "8110",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "8110 Type : F2",
                "brandName" => "Square D",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "120 DC",
                "desc" => 'Series A, 7 Electrical Interlocks (Aux. Contacts)',
                "additionalKeywords" => "8110F2",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/8110 F2.jpg"
            ],
            [
                "name" => "8110-A - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "(8110-A),(8110-DO-7-B), (8110-DO-8-C)",
                "modelNo" => "51033-467-50501E0 / 8110-DO-7 / 8110-D08-C",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "8110-A / 8110-DO-7 / 8110-D0-8",
                "brandName" => "Square D",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "0 / 2400/ 2500 / 5000",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => 'Type :  E, Series A, w/ 24 Pin Ctrl. Block',
                "additionalKeywords" => "B51033-468, 100636-B, 8110A",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/8110-A-102213-3.jpg"
            ],
            [
                "name" => "8110-DO-7 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "(8110-DO-7-B)/(8110-DO-8-C)",
                "modelNo" => "8110-DO-7 / 8110-D08-C",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "8110-DO-7 / 8110-D0-8",
                "brandName" => "Square D",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2500 / 5000",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => 'Ser. B, 3Ø, 60Cy., 50 MVA Amps : Int. Cap.,3.13 Amps Inrush, 0.61 Amps : Hold',
                "additionalKeywords" => "A5-1033-115-50",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/8110-DO-7-X2-021309-1.jpg"
            ],
            [
                "name" => "8110-DO-8 -360 Amp",
                "category" => "Contractors",
                "partModelNo" => "(8110-DO-8-B)/(8110-DO-8-X2)",
                "modelNo" => "A51033-110-55",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "8110-DO-8",
                "brandName" => "Square D",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000 / 2500",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => '',
                "additionalKeywords" => "8110-DO-8-B, 8110DO8",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "8110-V3540G - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "8110-V3540G-JPDWX22-D",
                "partNo" => "8110-V3540G",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "8110 Vacuum",
                "brandName" => "Square D",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => 'With Latching Mechanism, Bolt-in Class 8110 AC, Type : V3540G, Form JPDWX22, Series D, Max short circuit current 7300A @ 5kV.',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/8110-V3540G-vacuum.jpg"
            ],
            [
                "name" => "8110-DO-9 -360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "A51033-111-50",
                "partNo" => "8110-DO-9-B",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "8110-DO-9",
                "brandName" => "Square D",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000 / 2500",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => 'Series B unit',
                "additionalKeywords" => "8110DO9",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/8110-DO-9-B-021309-1.jpg"
            ],
            [
                "name" => "Retrofit - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "A5-1033-109-50",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "Retrofit",
                "brandName" => "Square D",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => 'Original: 8110, Type : DO-7, Series B',
                "additionalKeywords" => "51033-109-50",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/retrofit.jpg"
            ],
            [
                "name" => "HCV - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "(HCV-5HA)/(HCV-Retro)",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "HCV",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "400 / 360",
                "controlVoltage" => "120 / 115 AC",
                "desc" => '',
                "additionalKeywords" => "HCV5HAL, HCV-5HAL, HCV-5, HCV5",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/HCV-5HA-021109-1.jpg"
            ],
            [
                "name" => "CV - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "(CV-5HA)/(CV-5HAL)",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CV",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "120 / 115 AC",
                "desc" => '(IC)',
                "additionalKeywords" => "CV5HA, CV-5HA, CV-5HAL, 3J9G0001-A",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CV-5HAL-061013-1.jpg"
            ],
            [
                "name" => "CV - 300 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "J-GAT",
                "partNo" => "CV452-J-GAT",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CV452J",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2300",
                "amps" => "300",
                "controlVoltage" => "120 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CV452-J-GAT-041515-3.jpg"
            ],
            [
                "name" => "CV - 150 Amp",
                "category" => "Contractors",
                "partModelNo" => "CV432H-H",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CV",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "3300 / 2500",
                "amps" => "450",
                "controlVoltage" => "110 DC",
                "desc" => '',
                "additionalKeywords" => "3703292FB1, CV432H",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CV432H-H-021209-2.jpg"
            ],
            [
                "name" => "DV - 400 Amp",
                "category" => "Contractors",
                "partModelNo" => "(DV-21DM-10)/(LCDV-00DM-10)/(DV-21DL-11)/(LCDV-00SM-10)/(DV-15KA00)/(DV-21SL-11)/(DV-21SM-10)/(DV-25DL-11)",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "DV",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2400",
                "amps" => "400",
                "controlVoltage" => "120 AC",
                "desc" => '',
                "additionalKeywords" => "BK53633-010-F05B, DV-21DM",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/DV-21DL-11-021109-1.jpg"
            ],
            [
                "name" => "CV-6 - 720 Amp",
                "category" => "Contractors",
                "partModelNo" => "CV-6KAU",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CV-6",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "7200",
                "amps" => "720",
                "controlVoltage" => "100 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CV-6KAU-091314-1.jpg"
            ],
            [
                "name" => "CV452 - 300 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "J-GAT",
                "partNo" => "CV452-J-GAT",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CV452J",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2300",
                "amps" => "300",
                "controlVoltage" => "120 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CV452-J-GAT-041515-3.jpg"
            ],
            [
                "name" => "CV461M- 720 Amp",
                "category" => "Contractors",
                "partModelNo" => "CV461M-KAT",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CV461M",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "720",
                "controlVoltage" => "115 / 120 AC",
                "desc" => '',
                "additionalKeywords" => "CV461M",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CV461M-KAT-021209-4.jpg"
            ],
            [
                "name" => "CV211 - 600 Amp",
                "category" => "Contractors",
                "partModelNo" => "CV211-JAT",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CV211",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "1500",
                "amps" => "600",
                "controlVoltage" => "115 / 120 AC",
                "desc" => '3Ø',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "88 pounds",
                "image" => "img/product/Contactors/CV211-JAT-101216-1 (1).jpg"
            ],
            [
                "name" => "CV451J - 450 Amp",
                "category" => "Contractors",
                "partModelNo" => "(CV451J-HAT)/(CV452-J-GAT)",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CV451J",
                "brandName" => "Toshiba",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed / Roll-In",
                "primaryVoltage" => "5000 / 2300",
                "amps" => "450 / 300",
                "controlVoltage" => "115 / 120 AC",
                "desc" => '3Ø, 30MVA',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/CV452-J-GAT-041515-3.jpg"
            ],
            [
                "name" => "DF - 700 Amp",
                "category" => "Contractors",
                "partModelNo" => "(DF-325M000)/(DV-21SM-10)",
                "modelNo" => "# / DV-21SM-10",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "DF",
                "brandName" => "Toshiba",
                "vacuumAir" => "",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2400 / 2400",
                "amps" => "700 / 400",
                "controlVoltage" => "",
                "desc" => 'Draw Out, Double Barrel Fuse Clips',
                "additionalKeywords" => "DF-325M, DF-325M000",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/DF-700amp.jpg"
            ],
            [
                "name" => "SJA-50 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "(SJA50VW430) / (SJA50VW430-A) / (SJA50VM430)",
                "modelNo" => "VMAN3FN4G1- / 2197A01G27 / 2197A01G01",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SJA-50",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => '',
                "additionalKeywords" => "2147A45G01, 2147A45G02, 2147A45G03, 2147A45G04, VMAN, SJA50VW430",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/SJA50VW430-021309-1.jpg"
            ],
            [
                "name" => "SJA-50 - 650 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SJA-72 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SJS-50 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "B",
                "partNo" => "SJS50VW420",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SJS-50",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => '2Ø Vacuum Contactor',
                "additionalKeywords" => "2147A45G31, 2147A45G32, 2147A45G33, 2147A45G34, SJS50VW420, SBAR2NN4G1, C150RB44G2",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/SJS50VW420-032514-3.jpg"
            ],
            [
                "name" => "LF-25 - 180 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "2018A17G01",
                "partNo" => "LF25H230",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "LF-25",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "",
                "amps" => "180",
                "controlVoltage" => "115 AC",
                "desc" => '1 Closing Coil',
                "additionalKeywords" => "LF25H230",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/LF25H230-020409-2.jpg"
            ],
            [
                "name" => "LF-50 - 180 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "LF-50 - 360 Amp",
                "category" => "Contractors",
                "partModelNo" => "(LF50H430) / (LF50H430L) / (LF50H403) / (LF50H420) / (LF50H430C)",
                "modelNo" => "490A813G01",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "LF-50",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2300 / 5000",
                "amps" => "360",
                "controlVoltage" => "100 DC",
                "desc" => '3-Pole Air Break Unit',
                "additionalKeywords" => "LF50H430",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/LF50H430-020209-4.jpg"
            ],
            [
                "name" => "LF-50 - 630 Amp",
                "category" => "Contractors",
                "partModelNo" => "(LF50H730) / (LF50H750)",
                "modelNo" => "2044A51G02",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "LF-50",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "630",
                "controlVoltage" => "115",
                "desc" => '',
                "additionalKeywords" => "LF50H730",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => "img/product/Contactors/LF50H730-050912-1.jpg"
            ],
            [
                "name" => "H230-D - 200 Amp",
                "category" => "Contractors",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "type" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
        ]);
    }
}
