<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class productSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('product')->insert([
            [
                "name" => "1502 vacuum - 400 amp",
                "partModelNo" => "1502-V4C1D1",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502 Vacuum",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "desc" => 'Series "A"',
                "additionalKeywords" => "VZ4-PE-C 5000, 1502-V4C1D1",
                "price" => "* please call or request quote",
                "shippingWeight" => "46 pounds",
                "image" => "img/contractor.png"
            ],
            [
                "name" => "1502 vacuum - 400 amp, Gray-plastic",
                "partModelNo" => "(1502-V4CBD-1) / (1502-V4DBDA-1) / (1502-VC4DBDB-0) / (1502-V4CCD-1)",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502 Vacuum",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "(2400 / 5000) - (2500/7200) - (2500/5000)",
                "amps" => "360 - 400",
                "controlVoltage" => "120 AC",
                // "desc" => '',
                "additionalKeywords" => "1502-V4CBD1-1",
                "price" => "* please call or request quote",
                "shippingWeight" => "46 pounds",
                "image" => ""
            ],
            [
                "name" => "1502 vacuum - 450 amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "desc" => "",
                "additionalKeywords" => "",
                "price" => "",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "1502 vacuum - 800 amp",
                "partModelNo" => "(1502-VC8DXDA-1) / (1502-V8DXDA-1)",
                "modelNo" => "Series E",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502 Vacuum",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "2500 / 7200",
                "amps" => "800",
                "desc" => "3Ø, 50/60Hz, Interrupting Capacity 12000Amp., Altitude 0-1000M",
                "additionalKeywords" => "Rockwell Automation",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "1502 vacuum - 800 amp",
                "partModelNo" => "1502-V8C6D1",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502 Vacuum",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "2500 / 7200",
                "amps" => "800",
                "desc" => 'Series A, 3 φ, Interrupting Rate: 11',
                "additionalKeywords" => "VZ8-PE-C",
                "price" => "* please call or request quote",
                "shippingWeight" => "122 pounds",
                "image" => ""
            ],
            [
                "name" => "Allen Bradley 1500 - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "1502 - 400 Amp",
                "partModelNo" => "(1502-A4C3D1) / (1502-A4C3D3)",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "1502",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "5000 / 2500",
                "amps" => "400",
                "desc" => '',
                "additionalKeywords" => "Centerline, 1502A4C3D1",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Allen Bradley - 1502 -800 Amp",
                "partModelNo" => "",
                "modelNo" => "A",
                "partNo" => "1502-A8C4D3",
                "UNSPSC" => "39121529",
                "contractorType" => "1502",
                "brandName" => "Allen Bradley",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "800",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Allen Bradley - 1152 - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Allis Chalmers - 25-118-537-501 Model - 400 Amp - 5000 / 2500 Volt Contactor",
                "partModelNo" => "",
                "modelNo" => "25-118-537-501",
                "partNo" => "456-D (black plastic arch chute)",
                "UNSPSC" => "39121529",
                "contractorType" => "456-D (Black Plastic Arch Chute)",
                "brandName" => "Allis Chalmers",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000 / 2500",
                "amps" => "400",
                "controlVoltage" => "230 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Allis Chalmers - 14-514-449 Model - 400 Amp - 5000 / 2500 Volt Contactor",
                "partModelNo" => "",
                "modelNo" => "14-514-449",
                "partNo" => "456-D (older gray arch chute)",
                "UNSPSC" => "39121529",
                "contractorType" => "456-D",
                "brandName" => "Allis Chalmers",
                "vacuumAir" => "",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000 / 2500",
                "amps" => "400",
                "controlVoltage" => "90 DC",
                "desc" => '0.75kVA, w/ 2 Barrel Fuse Clips',
                "additionalKeywords" => "456D, 2-4470-4224-1, 14-514-449, 456D",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "Allis Chalmers - 256-1 Model - 200 Amp - 5000 Volt Contactor",
                "partModelNo" => "256-1",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "256-1",
                "brandName" => "Allis Chalmers",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "200",
                "controlVoltage" => "",
                "desc" => 'Obsolete',
                "additionalKeywords" => "256",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SL-50 - (200-400 Amp)",
                "partModelNo" => "(SL50W430)/(SL50F230)/(SL50F430)/(SL50W230)/(SL50W430B)",
                "modelNo" => "A / B",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SL-50",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In / Slide-In",
                "primaryVoltage" => "2400 / 7200 - 4160",
                "amps" => "200 - 400",
                "controlVoltage" => "120 AC",
                "desc" => '3Ø, 60Hz, BIL 60kV, Control VA Inrush 600 Seal 30, Max. Intrptg Capacity 8500 A, Dropout Time 250 mSec, Altitude -1000m to +2000m, G.O. HUDT55275-001',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "112 pounds",
                "image" => ""
            ],
            [
                "name" => "SL-72 - 400 Amp",
                "partModelNo" => "(SL72S) / (SL72B)",
                "modelNo" => "A",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SL72S4",
                "brandName" => "Eaton",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "4160",
                "amps" => "400",
                "controlVoltage" => "120 AC",
                "desc" => 'Dropout Time 130 mSec, 3Ø, 60kV BIL, Control VA Inrush 1000 Seal 40',
                "additionalKeywords" => "SL72S4H3L",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SLN - (200-400 Amp)",
                "partModelNo" => "(SLN011S5A-220)/(SLN014S7A-550)",
                "modelNo" => "B",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "SLN",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '7.2Kv 160A VACUUM CONTACTOR',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SJA-25 - 360 Amp",
                "partModelNo" => "",
                "modelNo" => "VMAN3FN4A1-T1",
                "partNo" => "SJA25VW430",
                "UNSPSC" => "39121529",
                "contractorType" => "SJA-25",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2500",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => 'Model C, 3Ø, 60Hz',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SJA-50 (360-400 Amp)",
                "partModelNo" => "",
                "modelNo" => "VMAN3FN4E1-TX",
                "partNo" => "SJA50",
                "UNSPSC" => "39121529",
                "contractorType" => "SJA-50",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SJA-25 - 720 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SJO / SJ-720 - 720 Amp",
                "partModelNo" => "",
                "modelNo" => "9088A08V02",
                "partNo" => "SJ072VW830",
                "UNSPSC" => "39121529",
                "contractorType" => "SJ-720",
                "brandName" => "Westinghouse",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "7200 / 2600",
                "amps" => "720",
                "controlVoltage" => "220 / 240 AC",
                "desc" => '800 Amp, The Cutler-Hammer SJ vacuum model replaces the Westinghouse LF air break model. PN: 9088A08V02',
                "additionalKeywords" => "SJO72VW830, 9910D55 (vacuum bottle), (Vac Bottle W/Assembly), 2147A88G12",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "SJS-50 - 360 Amp",
                "partModelNo" => "",
                "modelNo" => "1A48747G01",
                "partNo" => "SJS50VW430",
                "UNSPSC" => "39121529",
                "contractorType" => "SJS-50",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => '',
                "additionalKeywords" => "2147A45G21, 2147A45G22, 2147A45G23, 2147A45G24, 5259C33 (vacuum bottle), SJS50VW430",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "9950 - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "VMAN3FN4A1-T1",
                "partNo" => "SJA25VW430",
                "UNSPSC" => "39121529",
                "contractorType" => "SJA-25",
                "brandName" => "Cutler-Hammer",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "2500",
                "amps" => "360",
                "controlVoltage" => "120 AC",
                "desc" => 'Model C, 3Ø, 60Hz',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "C80 - 1350 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "CR193B - 400 Amp",
                "partModelNo" => "(CR193B)/(CR193)",
                "modelNo" => "CR193B110L001022R",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CR193B",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "7200 / 2300",
                "amps" => "400",
                "controlVoltage" => "120 AC / 115 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "CR193C - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "CR193C110L005050U",
                "partNo" => "CR193C",
                "UNSPSC" => "39121529",
                "contractorType" => "CR193C",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "800",
                "controlVoltage" => "115 DC",
                "desc" => '800A, 5000V, VACUUM CONTACTOR',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "CR193D - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "CR193D110L005050R",
                "partNo" => "CR193D",
                "UNSPSC" => "39121529",
                "contractorType" => "CR193D",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "115 DC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "CR193V - 400 Amp",
                "partModelNo" => "(CR193V)/(CR193VC4)/(CR193VB)",
                "modelNo" => "VC4AB3A413AAB/VB4AB2A412AA02A",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "CR193VC",
                "brandName" => "General Electric",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => 'Limitamp Vacuum Conversion',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "CR193WB - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC-302 - 400 Amp,Wheels",
                "partModelNo" => "(IC302AA4)/(IC-302AB4)/(IC-302AC4)/(IC-302BB4)/(IC-302CB4)/(IC-302EAA4AA1A47AA2A)",
                "modelNo" => "IC302AA4AA3A02AA2A / IC302AB4AB3A47AA28 / IC302AC4AC2A02AA2A / IC302BB4AB2A312AA2A / IC302CB4AB2A02CA2A",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC302A",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In /Roll-In",
                "primaryVoltage" => "5000 / 2300 / 4800",
                "amps" => "400",
                "controlVoltage" => "115 AC / 230 AC / 76DC",
                "desc" => '',
                "additionalKeywords" => "0528X0534R02SA01, IC302A, IC302AA4",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC-302 - 700 Amp",
                "partModelNo" => "(IC302)/(	IC302EC7)/(IC302EB7)",
                "modelNo" => "IC302AA4AA3A02AA2A",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC-302A",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "2300 / 5000",
                "amps" => "400",
                "controlVoltage" => "115 AC / 115 DC",
                "desc" => '',
                "additionalKeywords" => "0482X0176R01-A02",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC-302 - 400 Amp,Slider",
                "partModelNo" => "(IC302)/(IC302B)",
                "modelNo" => "IC302AA4AA3A02AA2A",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC-302A",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "2300 / 2400",
                "amps" => "400",
                "controlVoltage" => "115 AC / 230AC",
                "desc" => '',
                "additionalKeywords" => "0482X0176R01-A02",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC-2814-2 - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "IC2814E210B47",
                "partNo" => "IC2814E210",
                "UNSPSC" => "39121529",
                "contractorType" => "IC-2812-E",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Slide-In",
                "primaryVoltage" => "2400",
                "amps" => "400",
                "controlVoltage" => "230 AC",
                "desc" => 'Includes: Grounding bars',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC-2814 - 700 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC-2812-E - 400 Amp",
                "partModelNo" => "(IC-2812E100)/(IC2812E)/(IC-2812E100B)",
                "modelNo" => "IC-2812-E100DA47",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC-2812-E",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-In",
                "primaryVoltage" => "5000",
                "amps" => "360",
                "controlVoltage" => "230 AC",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "IC-2814-E - (200-400 Amp)",
                "partModelNo" => "(IC2814E)/(IC2814E150)/(IC2814E22)/(IC2814E230B2)/(IC2814E621)/(IC2814220E)/(IC-2814E120AC)/(IC2814E210B)/(IC2814E220)/(IC2814E220B)/(IC2814E220C)/(IC2814E221B)/(IC2814E221C)/IC2814E230B)/(IC-2814E230B)/(IC2814E230C)/(IC-2814E230C)/(IC2814E230EB47A2)/(IC-2814E231B)/(IC2814E231C)/(IC-2814E231E)/(IC-2814E620B)",
                "modelNo" => "IC2814E220B22",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "IC2814-E",
                "brandName" => "General Electric",
                "vacuumAir" => "Air",
                "rollSlideFixed" => "Roll-in",
                "primaryVoltage" => "4160",
                "amps" => "400",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "7840 Vacuum - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "7850 Air - 360 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U032A50-76 - 200 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U034A50-125 - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U034A50-76 - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "MVC77U034A50-76",
                "partNo" => "MVC77U034A50-76",
                "UNSPSC" => "39121529",
                "contractorType" => "MVC77",
                "brandName" => "Joslyn Clark",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "400",
                "controlVoltage" => "120 AC",
                "desc" => '400A, 5kVA, COIL 120vAC',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U034A72-76 - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U035A50-76 - 500 Amp",
                "partModelNo" => "MVC77U035A50-76",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "39121529",
                "contractorType" => "MVC77",
                "brandName" => "Joslyn Clark",
                "vacuumAir" => "Vacuum",
                "rollSlideFixed" => "Fixed",
                "primaryVoltage" => "5000",
                "amps" => "500",
                "controlVoltage" => "120",
                "desc" => '3Ø, 50/60Hz, Impulse BIL 60kV',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "MVC77U036A72-76 - 400 Amp",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
            [
                "name" => "",
                "partModelNo" => "",
                "modelNo" => "",
                "partNo" => "",
                "UNSPSC" => "",
                "contractorType" => "",
                "brandName" => "",
                "vacuumAir" => "",
                "rollSlideFixed" => "",
                "primaryVoltage" => "",
                "amps" => "",
                "controlVoltage" => "",
                "desc" => '',
                "additionalKeywords" => "",
                "price" => "* please call or request quote",
                "shippingWeight" => "",
                "image" => ""
            ],
        ]);
    }
}
